version: "3"

services:
    nginx:
        build:
          context: ./requirements/nginx
          dockerfile: Dockerfile
        container_name: nginx
        env_file: .env
        volumes:
            - /home/anbourge/data/wordpress:/var/www/html
        depends_on:
            - wordpress
        networks:
            - inception
        ports:
            - 443:443
        restart: always

    wordpress:
        build:
          context: ./requirements/wordpress
          dockerfile: Dockerfile
        container_name: wordpress
        env_file: .env
        volumes:
            - /home/anbourge/data/wordpress:/var/www/html
        depends_on:
            - mariadb
        networks:
            - inception
        restart: always

    mariadb:
        build:
          context: ./requirements/mariadb
          dockerfile: Dockerfile
        container_name: mariadb
        env_file: .env
        volumes:
            - /home/anbourge/data/database:/var/lib/mysql
        networks:
            - inception
        restart: always

networks:
    inception: